### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by h12w** [liipx/gdict#2]
曾经试图用Google词典和图片搜索做个背单词工具，但是Google的反爬做得太好，直接爬取的各种尝试失败后，最后只得用[iframe嵌入来实现](https://github.com/h12w/word-list)，所以用有道词典也是一个很好的思路。

词汇学习有几个功能点比较重要：
1. 国际音标和发音（已支持）
2. 英英解释（包括词根解释）
3. 例句
4. 图示（好的图示比较难做）
5. 方便地建立生词表，复习和标记

**Comment by liipx** [comment]
2. 英英解释目前没有发现有比较好的API，等有时间我看看找个时间看看爬虫行不行
3. 例句稍后我会通过金山的爱词霸接口来支持
4. 是的
5. 正在支持

**Comment by liipx** [comment]
生词表功能无限期delay

**Comment by h12w** [comment]
嗯，生词表不一定要做在词典里，也可以是另外一个工具。因为词典已经是命令行工具了，容易和其他工具集成在一起。
