### ISSUE TITLE
issue for the picture

### ISSUE THREAD

**Issue by LPX-E5BD8** [liipx/gdict#4]
![image](https://user-images.githubusercontent.com/39460745/41031204-b6a57410-69b2-11e8-97c7-029a75458e85.png)

**Comment by liipx** [comment]
![image](https://user-images.githubusercontent.com/39460745/41031258-d489d8c2-69b2-11e8-8301-2fd04e54cb9d.png)

**Comment by liipx** [comment]
![image](https://user-images.githubusercontent.com/39460745/41031328-f0ae751c-69b2-11e8-8709-1498423d3720.png)

**Comment by liipx** [comment]
<img width="573" alt="wechatimg1" src="https://user-images.githubusercontent.com/39460745/44953434-f790ff80-aec7-11e8-82cf-271f5dbeccd1.png">

**Comment by liipx** [comment]
![image](https://user-images.githubusercontent.com/39460745/44953473-48085d00-aec8-11e8-813e-f9fe3ea32558.png)
